/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package filetobyte;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // @Test void appHasAGreeting() {
    //     App classUnderTest = new App();
    //     assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    // }
    // @Test void appHex(){
    //     App.hex((byte)-1);
    // }
}
